site_name: AnaxExp documentation
site_description: AnaxExp documentation
site_author: AnaxExp, Inc.
site_url: https://docs.anaxexp.com

repo_name: anaxexp/docs
repo_url: https://github.com/anaxexp/docs

copyright: AnaxExp, Inc.

extra:
  social:
    - type: globe
      link: https://anaxexp.com
    - type: github-alt
      link: https://github.com/anaxexp
    - type: twitter
      link: https://twitter.com/AnaxExpHQ

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  custom_dir: 'theme'

extra_css: ["assets/anaxexp.css"]
extra_javascript: ["assets/intercom.js","assets/anaxexp.js"]

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs

pages:
  - Home: index.md
  - Billing: billing.md
  - Development: dev.md
  - FAQ: faq.md
  - Status: status.md
  - Support: support.md
  - Troubleshooting: troubleshooting.md
  - User roles: roles.md
  - Apps:
    - New app: apps/new.md
    - Instances: apps/instances.md
    - Deployment: apps/deploy.md
    - Domains: apps/domains.md
    - Backups: apps/backups.md
    - Logging: apps/logs.md
    - Post-deployment scripts: apps/post-deployment-scripts.md
  - Infrastructure:
    - Overview: infrastructure/index.md
    - Connecting server: infrastructure/connecting-server.md
    - Containers: infrastructure/containers.md
    - Monitoring: infrastructure/monitoring.md
    - Environment variables: infrastructure/env-vars.md
    - Disk: infrastructure/disk.md
    - Maintenance: infrastructure/maintenance.md
    - Security: infrastructure/security.md
    - HSTS: infrastructure/hsts.md
    - UFW: infrastructure/ufw.md
    - CLI: infrastructure/cli.md
  - Stacks:
    - Overview: stacks/index.md
    - Configuration: stacks/config.md
    - Template: stacks/template.md
    - Maintenance: stacks/maintenance.md
    - Drupal:
      - Overview: stacks/drupal/index.md
      - Containers: stacks/drupal/containers.md
      - Local environment: stacks/drupal/local.md
      - Changelog: stacks/drupal/changelog.md
    - WordPress:
      - Overview: stacks/wordpress/index.md
      - Containers: stacks/wordpress/containers.md
      - Local environment: stacks/wordpress/local.md
      - Changelog: stacks/wordpress/changelog.md
    - PHP:
      - Overview: stacks/php/index.md
      - Containers: stacks/php/containers.md
      - Local environment: stacks/php/local.md
    - GitLab:
      - Overview: stacks/gitlab/index.md
      - Changelog: stacks/gitlab/changelog.md
    - HTML: stacks/html/index.md
    - Matomo: stacks/matomo/index.md
    - Cachet: stacks/cachet/index.md
    - MariaDB: stacks/mariadb/index.md
    - PostgreSQL: stacks/postgres/index.md
    - Solr: stacks/solr/index.md
    - Solr for Drupal: stacks/solr-drupal/index.md
    - OpenSMTPD: stacks/opensmtpd/index.md
    - Elasticsearch: stacks/elasticsearch/index.md
    - AthenaPDF: stacks/athenapdf/index.md
    - Redis: stacks/redis/index.md
    - Varnish: stacks/varnish/index.md
    - Jenkins: stacks/jenkins/index.md
    - Docker registry: stacks/docker-registry/index.md
    - Slackin: stacks/slackin/index.md

  - Integrations:
    - AWS: integrations/aws.md
    - Azure: integrations/azure.md
    - BitBucket: integrations/bitbucket.md
    - CloudFlare: integrations/cloudflare.md
    - DigitalOcean: integrations/digitalocean.md
    - Docker registry: integrations/docker-registry.md
    - GCP: integrations/gcp.md
    - GitHub: integrations/github.md
    - GitLab: integrations/gitlab.md
    - Linode: integrations/linode.md
    - SendGrid: integrations/sendgrid.md
    - Custom provider: integrations/custom.md
  - Cluster:
    - Kubernetes cluster: cluster/index.md
